#line 2 "/Users/miguel/Downloads/make/epan/protobuf_lang_scanner.c"
#line 2 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
/* Include this before everything else, for various large-file definitions */
#include "config.h"



#line 9 "/Users/miguel/Downloads/make/epan/protobuf_lang_scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE protobuf_langrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE protobuf_langlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via protobuf_langrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void protobuf_langrestart (FILE *input_file ,yyscan_t yyscanner );
void protobuf_lang_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE protobuf_lang_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void protobuf_lang_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void protobuf_lang_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void protobuf_langpush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void protobuf_langpop_buffer_state (yyscan_t yyscanner );

static void protobuf_langensure_buffer_stack (yyscan_t yyscanner );
static void protobuf_lang_load_buffer_state (yyscan_t yyscanner );
static void protobuf_lang_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER protobuf_lang_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE protobuf_lang_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE protobuf_lang_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE protobuf_lang_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *protobuf_langalloc (yy_size_t ,yyscan_t yyscanner );
void *protobuf_langrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void protobuf_langfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer protobuf_lang_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        protobuf_langensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            protobuf_lang_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        protobuf_langensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            protobuf_lang_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define protobuf_langwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[206] =
    {   0,
        0,    0,    0,    0,   74,   72,   71,   71,   23,    1,
       29,   28,   22,   72,    2,    3,   17,   15,   33,   16,
       32,   18,   61,   61,   34,   31,   35,   14,   36,   30,
       64,    4,    5,   25,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,    6,   20,    7,   24,   70,   70,
       70,    9,    0,   65,    0,    0,   21,    0,   66,    0,
        0,   13,   68,   67,   64,   62,   64,   61,   26,   12,
       10,    8,   11,   27,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   58,
       64,   19,   70,   70,   69,    0,   65,    0,    0,   66,

        0,    0,    0,   67,   63,   64,   64,   64,   64,   47,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   55,
       64,   64,   64,   64,    0,    0,   49,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   39,    0,    0,   64,   50,   64,   64,   46,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
        0,    0,   51,   64,   38,   64,   42,   64,   40,   64,
       64,   64,   64,   64,   56,   37,    0,    0,    0,    0,
       64,   53,   64,   41,   64,   64,   64,   57,   54,   59,
       59,   60,   60,   59,   59,   60,   60,   64,   44,   45,

       43,   48,   64,   52,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   20,   20,   20,   20,   23,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   30,   30,   30,   30,   30,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   32,   31,   31,
       33,   34,   35,   36,   31,    1,   37,   38,   39,   40,

       41,   42,   43,   31,   44,   31,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   31,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    1,    1,
        1,    1,    5,    6,    1,    6,    6,    1,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    6,
        6,    6,    1,    1,    1,    1,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[214] =
    {   0,
        0,    0,   61,   62,  335,  336,  336,  336,  307,   60,
      336,  336,  324,   57,  336,  336,  336,  305,  336,  336,
      336,   55,   50,   57,  336,  336,   57,  304,   59,  336,
        0,  336,  336,  336,   40,  278,  282,   52,   42,   44,
       54,   55,  279,  286,  336,  265,  336,  336,  322,  321,
      305,  336,   91,  316,   94,   95,  336,   92,   93,  105,
       96,  336,  336,    0,    0,   97,  130,  101,  336,  336,
      336,  336,  336,  336,  266,  266,  270,  268,  267,  263,
      274,  260,  274,  274,   81,  272,  258,  257,  260,    0,
      270,  336,  303,  302,  336,   99,  106,  107,  130,  127,

      128,  148,  132,    0,    0,  257,  262,  247,  252,    0,
      247,  250,  254,  252,  250,  254,  239,  252,  237,    0,
      235,  249,  235,  243,  139,  146,    0,  239,  236,  233,
      247,  241,  233,  244,  236,  242,  234,  225,  224,  228,
      234,  228,    0,  140,  149,  104,    0,  205,  213,    0,
      201,  204,  202,  178,  179,  173,  180,  188,  179,  166,
      169,  174,    0,  179,    0,  181,  184,  179,    0,  178,
      177,  176,  162,  173,    0,    0,  182,  191,  196,  199,
      163,    0,  165,    0,  167,  159,  154,    0,    0,  172,
      170,  171,  179,  336,  153,  336,  176,  117,    0,    0,

        0,    0,  102,    0,  336,  233,  239,  245,  137,  251,
      257,  263,  269
    } ;

static yyconst flex_int16_t yy_def[214] =
    {   0,
      205,    1,  206,  206,  205,  205,  205,  205,  205,  207,
      205,  205,  205,  208,  205,  205,  205,  205,  205,  205,
      205,  205,  209,  209,  205,  205,  205,  205,  205,  205,
      209,  205,  205,  205,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  205,  205,  205,  205,  210,  210,
      205,  205,  207,  205,  211,  207,  205,  208,  208,  212,
      208,  205,  205,  213,  209,  209,  209,  209,  205,  205,
      205,  205,  205,  205,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  205,  210,  210,  205,  207,  207,  211,  207,  208,

      208,  212,  208,  213,   67,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  207,  208,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  207,  208,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      207,  208,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  207,  207,  208,  208,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  205,
      207,  205,  207,  205,  208,  205,  208,  209,  209,  209,

      209,  209,  209,  209,    0,  205,  205,  205,  205,  205,
      205,  205,  205
    } ;

static yyconst flex_int16_t yy_nxt[400] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       24,   24,   24,   25,   26,   27,   28,   29,   30,   31,
       31,   31,   32,    6,   33,   34,   31,   31,   31,   31,
       35,   31,   36,   37,   31,   31,   38,   31,   39,   40,
       31,   41,   42,   43,   31,   31,   44,   31,   31,   45,
       46,   47,   48,   50,   50,   54,   59,   63,   66,   66,
       66,   66,   64,   51,   51,   68,   68,   68,   68,   68,
       83,   67,   69,   70,   71,   73,   74,   75,   79,   81,
       60,   82,   80,   55,   85,   87,   54,   76,   84,   97,

       54,   59,  100,   86,   54,   59,   61,   67,   88,   56,
       58,   97,   97,   89,  100,   66,   66,   66,   66,   68,
       68,   68,   68,   68,   55,   60,   60,   98,   55,   60,
      116,  117,   55,  118,  119,   54,  100,   59,  102,   55,
       98,   59,   65,  163,   54,   54,   99,  103,  105,  105,
      105,  105,  105,   58,  204,   59,  164,  100,   59,  105,
       60,   60,  100,   55,  203,   60,  105,  105,  105,  105,
      105,  105,   55,   55,   54,   54,   53,   53,  125,   60,
      126,  102,   60,   59,   54,  100,   60,  190,  161,  177,
      178,  191,  144,  202,  179,  180,  192,  162,  201,  145,

      193,  194,   55,   55,  196,  195,  200,   60,  197,   60,
      199,  198,   55,  189,  188,   55,  187,  186,  185,  184,
      183,  182,  181,  176,   55,  175,  174,  173,  172,   60,
      171,  170,   60,   49,   49,   49,   49,   49,   49,   53,
      169,   53,   53,   53,   53,   58,  168,   58,  167,   58,
       58,   93,   93,   93,   93,  166,   93,   96,  165,   96,
       96,   96,   96,  101,  160,  101,  101,  101,  101,  104,
      159,  158,  104,  104,  104,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  132,  131,

      130,  129,  128,  127,   94,   94,  124,  123,  122,  121,
      120,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,   53,   95,   94,   94,   92,   91,   90,   78,   77,
       72,   62,   57,   52,  205,    5,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205

    } ;

static yyconst flex_int16_t yy_chk[400] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   10,   14,   22,   23,   23,
       23,   23,   22,    3,    4,   24,   24,   24,   24,   24,
       40,   23,   27,   27,   27,   29,   29,   35,   38,   39,
       14,   39,   38,   10,   41,   42,   53,   35,   40,   55,

       56,   58,   59,   41,   96,   61,   14,   23,   42,   10,
       60,   97,   98,   42,   60,   66,   66,   66,   66,   68,
       68,   68,   68,   68,   53,   58,   59,   55,   56,   61,
       85,   85,   96,   85,   85,   99,  100,  101,   60,   97,
       98,  103,  209,  146,  125,  144,   56,   61,   67,   67,
       67,   67,   67,  102,  203,  126,  146,  102,  145,   67,
      100,  101,  195,   99,  198,  103,   67,   67,   67,   67,
       67,   67,  125,  144,  161,  191,  192,  190,   99,  126,
      103,  102,  145,  162,  193,  197,  195,  177,  144,  161,
      161,  177,  125,  187,  162,  162,  178,  145,  186,  126,

      178,  179,  161,  191,  180,  179,  185,  162,  180,  197,
      183,  181,  193,  174,  173,  177,  172,  171,  170,  168,
      167,  166,  164,  160,  178,  159,  158,  157,  156,  179,
      155,  154,  180,  206,  206,  206,  206,  206,  206,  207,
      153,  207,  207,  207,  207,  208,  152,  208,  151,  208,
      208,  210,  210,  210,  210,  149,  210,  211,  148,  211,
      211,  211,  211,  212,  142,  212,  212,  212,  212,  213,
      141,  140,  213,  213,  213,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  124,  123,  122,
      121,  119,  118,  117,  116,  115,  114,  113,  112,  111,

      109,  108,  107,  106,   94,   93,   91,   89,   88,   87,
       86,   84,   83,   82,   81,   80,   79,   78,   77,   76,
       75,   54,   51,   50,   49,   46,   44,   43,   37,   36,
       28,   18,   13,    9,    5,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205

    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[74] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"

/*
 * We want a reentrant scanner.
 */
/*
 * We want to generate code that can be used by a reentrant parser
 * generated by Bison or Berkeley YACC.
 */
/*
 * We don't read interactively from the terminal.
 */
/*
 * We want to stop processing when we get to the end of the input.
 */
/*
 * The type for the state we keep for the scanner (and parser).
 */
/*
 * Prefix scanner routines with "protobuf_lang" rather than "yy", so this scanner
 * can coexist with other scanners.
 */
/*
 * We have to override the memory allocators so that we don't get
 * "unused argument" warnings from the yyscanner argument (which
 * we don't use, as we have a global memory allocator).
 *
 * We provide, as macros, our own versions of the routines generated by Flex,
 * which just call malloc()/realloc()/free() (as the Flex versions do),
 * discarding the extra argument.
 */
#define YY_NO_INPUT 1
#line 55 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
/* protobuf_lang_scanner.l
 *
 * C Protocol Buffers Language Lexer (for *.proto files)
 * Copyright 2019, Huang Qiangxiong <qiangxiong.huang@qq.com>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include "protobuf_lang_tree.h"
#include "protobuf_lang.h"

/*
 * Disable diagnostics in the code generated by Flex.
 */
DIAG_OFF_FLEX

/*
 * Sleazy hack to suppress compiler warnings in yy_fatal_error().
 */
#define YY_EXIT_FAILURE ((void)yyscanner, 2)

/*
 * Macros for the allocators, to discard the extra argument.
 */
#define protobuf_langalloc(size, yyscanner)        (void *)malloc(size)
#define protobuf_langrealloc(ptr, size, yyscanner)    (void *)realloc((char *)(ptr), (size))
#define protobuf_langfree(ptr, yyscanner)        free((char *)ptr)

int old_status;

/* error handling function defined in bison (*.y) file */
extern void
protobuf_langerrorv(void* yyscanner, protobuf_lang_state_t *state, const char *fmt, ...);

/* duplicate the text and keep the pointer in parser state for freeing later automatically */
static gchar*
strdup_and_store(void* yyscanner, const char* text);


#line 694 "/Users/miguel/Downloads/make/epan/protobuf_lang_scanner.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE protobuf_lang_state_t *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int protobuf_langlex_init (yyscan_t* scanner);

int protobuf_langlex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int protobuf_langlex_destroy (yyscan_t yyscanner );

int protobuf_langget_debug (yyscan_t yyscanner );

void protobuf_langset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE protobuf_langget_extra (yyscan_t yyscanner );

void protobuf_langset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *protobuf_langget_in (yyscan_t yyscanner );

void protobuf_langset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *protobuf_langget_out (yyscan_t yyscanner );

void protobuf_langset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t protobuf_langget_leng (yyscan_t yyscanner );

char *protobuf_langget_text (yyscan_t yyscanner );

int protobuf_langget_lineno (yyscan_t yyscanner );

void protobuf_langset_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * protobuf_langget_lval (yyscan_t yyscanner );

void protobuf_langset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int protobuf_langwrap (yyscan_t yyscanner );
#else
extern int protobuf_langwrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int protobuf_langlex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int protobuf_langlex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 101 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"

    /* operations or symbols (PT_ means PBL Token) */
#line 927 "/Users/miguel/Downloads/make/epan/protobuf_lang_scanner.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			protobuf_langensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				protobuf_lang_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		protobuf_lang_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 206 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 205 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 103 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_QUOTE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 104 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_LPAREN;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 105 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_RPAREN;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 106 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_LBRACKET;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 107 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_RBRACKET;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 108 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_LCURLY;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_RCURLY;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 110 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_EQUAL;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 111 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_NOTEQUAL;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 112 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_NOTEQUAL2;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_GEQUAL;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 114 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_LEQUAL;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_ASSIGN_PLUS;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_ASSIGN;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_PLUS;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_MINUS;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 119 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_MULTIPLY;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 120 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_DIV;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 121 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_LOGIC_OR;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_OR;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 123 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_LOGIC_AND;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 124 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_AND;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 125 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_NOT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_NEG;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 127 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_XOR;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 128 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_SHL;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 129 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_SHR;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 130 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_PERCENT;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 131 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_DOLLAR;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 132 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_COND;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 133 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_SEMICOLON;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 134 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_DOT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 135 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_COMMA;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 136 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_COLON;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 137 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_LESS;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 138 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
return PT_GREATER;
	YY_BREAK
/* key words */
case 37:
YY_RULE_SETUP
#line 141 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_SYNTAX;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 142 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_IMPORT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 143 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_WEAK;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 144 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_PUBLIC;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 145 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_PACKAGE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 146 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_OPTION;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 147 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_REQUIRED;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 148 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_OPTIONAL;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 149 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_REPEATED;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 150 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_ONEOF;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 151 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_MAP;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 152 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_RESERVED;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 153 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_ENUM;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 154 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_GROUP;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 155 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_EXTEND;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 156 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_EXTENSIONS;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 157 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_MESSAGE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 158 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_SERVICE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 159 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_RPC;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 160 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_STREAM;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 161 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_RETURNS;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 162 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_TO;
	YY_BREAK
/* key values */
case 59:
YY_RULE_SETUP
#line 165 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_PROTO2;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 166 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_PROTO3;
	YY_BREAK
/* intLit values */
case 61:
YY_RULE_SETUP
#line 169 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->u64val = g_ascii_strtoull(yytext, NULL, 10); return PT_DECIMALLIT;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 170 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->u64val = g_ascii_strtoull(yytext+1, NULL, 8); return PT_OCTALLIT;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 171 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->u64val = g_ascii_strtoull(yytext+2, NULL, 16); return PT_HEXLIT;
	YY_BREAK
/* Using extended identifier because we care only about position */
case 64:
YY_RULE_SETUP
#line 174 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = strdup_and_store(yyscanner, yytext); return PT_IDENT;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 175 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = g_strndup(yytext + 1, strlen(yytext) - 2); return PT_STRLIT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 176 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
yylval->sval = g_strndup(yytext + 1, strlen(yytext) - 2); return PT_STRLIT;
	YY_BREAK
/* comments */
case 67:
YY_RULE_SETUP
#line 179 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"

	YY_BREAK
case 68:
YY_RULE_SETUP
#line 180 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
{ old_status = YY_START; BEGIN COMMENT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 181 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
{ BEGIN old_status; }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 182 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"

	YY_BREAK
/* space & tab */
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 185 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"

	YY_BREAK
/* prevent flex jam */
case 72:
YY_RULE_SETUP
#line 187 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
{ protobuf_langerrorv(yyscanner, protobuf_langget_extra(yyscanner), "unexpected token in proto file!\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 189 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"
ECHO;
	YY_BREAK
#line 1394 "/Users/miguel/Downloads/make/epan/protobuf_lang_scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * protobuf_langlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( protobuf_langwrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of protobuf_langlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					protobuf_langrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			protobuf_langrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) protobuf_langrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 206 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 206 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 205);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					protobuf_langrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( protobuf_langwrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void protobuf_langrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        protobuf_langensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            protobuf_lang_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	protobuf_lang_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	protobuf_lang_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void protobuf_lang_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		protobuf_langpop_buffer_state();
	 *		protobuf_langpush_buffer_state(new_buffer);
     */
	protobuf_langensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	protobuf_lang_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (protobuf_langwrap()) processing, but the only time this flag
	 * is looked at is after protobuf_langwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void protobuf_lang_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE protobuf_lang_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) protobuf_langalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in protobuf_lang_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) protobuf_langalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in protobuf_lang_create_buffer()" );

	b->yy_is_our_buffer = 1;

	protobuf_lang_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with protobuf_lang_create_buffer()
 * @param yyscanner The scanner object.
 */
    void protobuf_lang_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		protobuf_langfree((void *) b->yy_ch_buf ,yyscanner );

	protobuf_langfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a protobuf_langrestart() or at EOF.
 */
    static void protobuf_lang_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	protobuf_lang_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then protobuf_lang_init_buffer was _probably_
     * called from protobuf_langrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void protobuf_lang_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		protobuf_lang_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void protobuf_langpush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	protobuf_langensure_buffer_stack(yyscanner);

	/* This block is copied from protobuf_lang_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from protobuf_lang_switch_to_buffer. */
	protobuf_lang_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void protobuf_langpop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	protobuf_lang_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		protobuf_lang_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void protobuf_langensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)protobuf_langalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in protobuf_langensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)protobuf_langrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in protobuf_langensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE protobuf_lang_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) protobuf_langalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in protobuf_lang_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	protobuf_lang_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to protobuf_langlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       protobuf_lang_scan_bytes() instead.
 */
YY_BUFFER_STATE protobuf_lang_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return protobuf_lang_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to protobuf_langlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE protobuf_lang_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) protobuf_langalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in protobuf_lang_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = protobuf_lang_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in protobuf_lang_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE protobuf_langget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int protobuf_langget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int protobuf_langget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *protobuf_langget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *protobuf_langget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t protobuf_langget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *protobuf_langget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void protobuf_langset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void protobuf_langset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "protobuf_langset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void protobuf_langset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "protobuf_langset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see protobuf_lang_switch_to_buffer
 */
void protobuf_langset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void protobuf_langset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int protobuf_langget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void protobuf_langset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * protobuf_langget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void protobuf_langset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* protobuf_langlex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int protobuf_langlex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) protobuf_langalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* protobuf_langlex_init_extra has the same functionality as protobuf_langlex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to protobuf_langalloc in
 * the yyextra field.
 */

int protobuf_langlex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    protobuf_langset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) protobuf_langalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    protobuf_langset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from protobuf_langlex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * protobuf_langlex_init()
     */
    return 0;
}

/* protobuf_langlex_destroy is for both reentrant and non-reentrant scanners. */
int protobuf_langlex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		protobuf_lang_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		protobuf_langpop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	protobuf_langfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        protobuf_langfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * protobuf_langlex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    protobuf_langfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#line 189 "/Users/miguel/Downloads/wireshark-3.4.2/epan/protobuf_lang_scanner.l"



static gchar*
strdup_and_store(void* yyscanner, const char* text) {
    return pbl_store_string_token(protobuf_langget_extra(yyscanner), g_strdup(text));
}

/*
 * Turn diagnostics back on, so we check the code that we've written.
 */
DIAG_ON_FLEX

