#define TOKEN_INVALID_CHAR                     1
#define TOKEN_INVALID_NUMBER                   2
#define TOKEN_ENDL                             3
#define TOKEN_PROTOCOL_TYPE                    4
#define TOKEN_START_SESSION                    5
#define TOKEN_DATA_MODE                        6
#define TOKEN_TIME_MODE                        7
#define TOKEN_HEADER_VER                       8
#define TOKEN_HEADER_CHAR                      9
#define TOKEN_START_TIME                      10
#define TOKEN_STOP_SESSION                    11
#define TOKEN_END_TIME                        12
#define TOKEN_MSG_DIR                         13
#define TOKEN_INT                             14
#define TOKEN_J1939_MSG_TYPE                  15
#define TOKEN_COLON                           16
#define TOKEN_MSG_TIME                        17
#define TOKEN_MSG_TYPE                        18
#define TOKEN_ERR_MSG_TYPE                    19
