#line 2 "/Users/miguel/Downloads/make/wiretap/busmaster_scanner.c"
#line 13 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
/* Include this before everything else, for various large-file definitions */
#include "config.h"



#line 9 "/Users/miguel/Downloads/make/wiretap/busmaster_scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE busmaster_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via busmaster_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void busmaster_restart (FILE *input_file ,yyscan_t yyscanner );
void busmaster__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE busmaster__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void busmaster__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void busmaster__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void busmaster_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void busmaster_pop_buffer_state (yyscan_t yyscanner );

static void busmaster_ensure_buffer_stack (yyscan_t yyscanner );
static void busmaster__load_buffer_state (yyscan_t yyscanner );
static void busmaster__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER busmaster__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE busmaster__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE busmaster__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE busmaster__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *busmaster_alloc (yy_size_t ,yyscan_t yyscanner );
void *busmaster_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void busmaster_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer busmaster__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        busmaster_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            busmaster__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        busmaster_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            busmaster__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define busmaster_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[451] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       46,   44,    1,    2,    2,   44,   34,   34,   34,   34,
       34,   34,   34,   34,   44,   44,   44,   44,   36,   38,
       22,    1,    3,    3,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   32,    1,    3,   32,   30,   31,
       24,    1,   25,   24,   24,   28,    1,   29,   28,   28,
        1,    2,    0,   34,    0,   34,    0,   34,   34,    0,
       34,    0,    0,    0,   34,    0,    0,    0,    0,    0,
        0,   35,    0,    0,   37,    0,   39,    3,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       30,   24,    1,   25,   24,   24,   28,    1,   29,   28,
       28,    4,    0,   43,    0,    0,    0,   42,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   13,    0,   14,
        0,    0,    0,    0,    0,    0,   24,   28,    0,    0,
        0,   42,    0,   43,   40,   41,    6,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   24,   28,    0,
        0,    0,    0,    0,    6,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   24,   28,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   24,   28,   33,    0,    0,    0,    0,

        5,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   24,   28,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   24,   28,   28,    0,    7,
        0,    0,    0,    0,    0,    0,    0,    0,   24,   28,
       28,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   24,   28,   28,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   16,    0,    0,   24,   28,
       28,    0,    0,    8,    0,   10,    0,    0,    0,    0,
        0,    0,   24,   28,   28,   15,    0,    0,   17,    0,
        0,    0,    0,    0,   24,   28,   28,    0,    9,    0,

        0,    0,    0,    0,   24,   28,   28,    0,    0,    0,
        0,    0,    0,   24,   28,   28,    0,    0,    0,    0,
        0,    0,   24,   28,   28,   12,    0,    0,    0,    0,
        0,   24,   28,   28,    0,    0,    0,    0,    0,   24,
       28,   28,    0,    0,   11,    0,    0,   24,   28,   28,
        0,    0,    0,    0,   24,   28,   28,    0,    0,    0,
        0,   24,   28,   28,    0,    0,    0,   19,   24,   28,
       28,    0,    0,   18,   24,   28,   28,    0,    0,   24,
       28,   28,    0,    0,   24,   28,   28,   20,    0,   24,
       28,   28,    0,   24,   28,   28,    0,    0,   24,   28,

       28,    0,    0,    0,   24,   24,   28,   28,    0,    0,
       24,   28,   28,    0,   23,   23,   28,   28,    0,   28,
       28,   21,   28,   28,   28,   28,    0,   28,   28,    0,
        0,   28,   28,   28,    0,   28,   28,   26,   26,    0,
       28,    0,    0,   28,   28,    0,   28,   27,   27,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    1,    1,    1,    1,    1,    6,
        7,    8,    1,    1,    9,    1,   10,   11,   12,   13,
       14,   13,   13,   13,   13,   13,   15,   16,    1,    1,
        1,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,    1,   39,   40,    1,
       41,    1,   42,    1,   43,    1,   44,   44,   44,   45,

       44,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   47,   48,    1,    1,    1,    1,   49,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[50] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    1,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[459] =
    {   0,
        0,    0,   48,   88,  128,  143,   55,   71,   95,  111,
      723,  724,   59,   82,  122,  714,  149,  672,  701,   37,
      155,  702,   36,    0,  684,  686,   45,   69,  102,  126,
      724,  102,  172,  176,  708,  697,  677,  692,  682,  690,
      676,  688,   81,  673,  724,  132,  185,  699,  188,  724,
        0,  148,  202,  206,  698,    0,  180,  210,  214,  697,
      218,  222,  696,  654,  217,    0,    0,  169,  673,  670,
        0,  680,  669,  663,  661,  667,  661,  662,  663,  657,
      656,  724,  670,  643,  724,  642,  724,  231,  679,  651,
      650,  665,  663,  643,  650,  652,  662,  643,  641,  668,

      226,    0,  240,  244,  248,  667,    0,  252,  256,  260,
      666,  724,  255,  724,  656,  629,  654,    0,  627,  648,
      632,  631,  621,  620,  218,  633,  634,  724,  657,  724,
      625,  643,  625,  622,   71,  240,  636,  635,  261,  635,
      637,    0,  631,  609,  724,  724,  275,  623,  633,  629,
      617,  611,  610,  624,  610,  611,  282,  612,  611,  280,
      621,  621,  601,  620,  295,  628,  598,  599,  616,  613,
      606,  625,  600,  592,  622,  302,  606,  605,  300,  607,
      592,  592,  602,  612,  583,  582,  581,  585,  577,  236,
      609,  608,  584,  606,  605,  305,  574,  574,  588,  578,

      724,  584,  583,  582,  574,  580,  576,  582,  569,  569,
      565,  576,  301,  558,  557,  587,  557,  585,  584,  583,
      570,  550,  554,  553,  560,  558,  564,  558,  550,  724,
      561,  303,  548,  546,  306,  555,  551,  550,  555,  535,
      565,  538,  538,  550,  554,  540,  533,  533,  544,  556,
      539,  536,  533,  527,  539,  535,  534,  533,  522,  536,
      520,  529,  527,  530,  529,  724,  520,  514,  513,  524,
      524,  519,  534,  724,  524,  724,  516,  508,  500,  504,
      503,  509,  510,  513,  493,  724,  492,  512,  724,  521,
      504,  504,  500,  517,  493,  485,  502,  493,  724,  499,

      511,  510,  509,  478,  507,  490,  492,  480,  491,  485,
      470,  470,  483,  485,  497,  484,  479,  462,  473,  472,
      475,  460,  477,  471,  457,  724,  471,  462,  460,  453,
      452,  449,  460,  463,  478,  461,  460,  445,  454,  458,
      449,  471,  441,  439,  724,  448,  441,  466,  449,  447,
      451,  462,  435,  435,  430,  428,  437,  425,  454,  429,
      416,  440,  451,  427,  433,  433,  410,  724,  415,  444,
      428,  440,  429,  724,  425,  425,  409,  435,  420,  433,
      422,  434,  430,  426,  425,  408,  409,  724,  394,  400,
      397,  381,  382,  278,  374,  375,  368,  331,  338,  368,

      358,  372,  345,  365,  352,  364,  347,  355,  351,  350,
      344,  344,  325,  336,  724,    0,  330,  319,  322,  320,
      307,  724,  317,  317,  285,  301,  359,  366,  300,  373,
      184,  380,  175,  144,  130,  120,  298,  724,    0,  387,
      394,  401,  102,  408,   87,   69,   54,  724,    0,  724,
      416,  419,  422,  425,   52,  428,  431,  434
    } ;

static yyconst flex_int16_t yy_def[459] =
    {   0,
      450,    1,  451,  451,  452,  452,  453,  453,  454,  454,
      450,  450,  450,  450,  450,  450,  450,   17,  455,  455,
      455,  455,  455,  455,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      456,  456,  450,  456,  456,  457,  457,  450,  457,  457,
      450,  450,  450,   17,  450,  455,  455,  455,  455,  450,
      455,  450,  450,  450,  455,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,

      450,  456,  456,  450,  456,  456,  457,  457,  450,  457,
      457,  450,  450,  450,  450,  450,  450,  458,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  456,  457,  450,  450,
      450,  458,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  456,  457,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  456,  457,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  456,  457,  450,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  456,  457,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  456,  457,  457,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  456,  457,
      457,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  456,  457,  457,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  456,  457,
      457,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  456,  457,  457,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  456,  457,  457,  450,  450,  450,

      450,  450,  450,  450,  456,  457,  457,  450,  450,  450,
      450,  450,  450,  456,  457,  457,  450,  450,  450,  450,
      450,  450,  456,  457,  457,  450,  450,  450,  450,  450,
      450,  456,  457,  457,  450,  450,  450,  450,  450,  456,
      457,  457,  450,  450,  450,  450,  450,  456,  457,  457,
      450,  450,  450,  450,  456,  457,  457,  450,  450,  450,
      450,  456,  457,  457,  450,  450,  450,  450,  456,  457,
      457,  450,  450,  450,  456,  457,  457,  450,  450,  456,
      457,  457,  450,  450,  456,  457,  457,  450,  450,  456,
      457,  457,  450,  456,  457,  457,  450,  450,  456,  457,

      457,  450,  450,  450,  456,  456,  457,  457,  450,  450,
      456,  457,  457,  450,  450,  456,  457,  457,  450,  457,
      457,  450,  457,  457,  457,  457,  450,  457,  457,  450,
      450,  457,  457,  457,  450,  457,  457,  450,  457,  450,
      457,  450,  450,  457,  457,  450,  457,  450,  457,    0,
      450,  450,  450,  450,  450,  450,  450,  450
    } ;

static yyconst flex_int16_t yy_nxt[774] =
    {   0,
       12,   13,   14,   15,   13,   12,   12,   16,   12,   12,
       17,   18,   18,   18,   18,   12,   19,   20,   21,   22,
       23,   24,   25,   12,   12,   12,   12,   12,   12,   26,
       12,   12,   12,   27,   12,   28,   12,   12,   12,   12,
       12,   12,   12,   24,   24,   24,   12,   29,   30,   32,
       33,   34,   32,   69,   66,   35,   52,   53,   54,   52,
       61,  449,   55,   61,   36,   37,   76,   38,   39,   77,
       70,   40,   52,   53,   54,   52,  448,   80,   55,   41,
       81,   42,   43,   62,   62,   62,   62,  155,   44,   32,
       33,   34,   32,   82,  447,   35,   57,   58,   59,   57,

       83,  156,   60,   61,   36,   37,   61,   38,   39,  446,
       84,   40,   57,   58,   59,   57,   97,   82,   60,   41,
       98,   42,   43,   62,   62,   62,   62,  439,   44,   46,
       33,   47,   46,   61,   86,   48,   61,  438,   49,   49,
       49,   49,   49,   50,   46,   33,   47,   46,   85,  103,
       48,  437,  103,   49,   49,   49,   49,   49,   50,   64,
       64,   64,   64,   64,   65,   66,   66,   66,   66,   66,
       66,   71,   87,   88,   88,   88,   88,   88,   88,   88,
       88,  108,  436,   72,  108,   73,   88,   88,   88,   88,
       74,  435,   66,   66,   66,  114,  114,   67,  101,  101,

      101,  101,  101,  104,  104,  104,  104,  105,  104,  105,
      105,  109,  109,  109,  109,  110,  109,  110,  110,   61,
      147,  147,   61,   62,   62,   62,   62,  113,  113,  113,
      113,  113,   88,   88,   88,   88,  101,  101,  101,  101,
      101,  103,  157,  157,  103,  104,  104,  104,  104,  105,
      104,  105,  105,  108,  207,  208,  108,  109,  109,  109,
      109,  110,  109,  110,  110,  113,  113,  113,  113,  113,
      139,  160,  160,  160,  160,  160,  165,  165,  165,  165,
      398,  399,  166,  176,  176,  176,  176,  427,  428,  166,
      160,  160,  160,  160,  160,  179,  165,  165,  165,  165,

      440,  441,  166,  176,  176,  176,  176,  434,  429,  166,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      227,  244,  249,  426,  425,  424,  250,  423,  245,  422,
      246,  228,  403,  403,  403,  403,  421,  420,  404,  405,
      403,  405,  405,  419,  418,  406,  403,  403,  403,  403,
      417,  416,  404,  405,  403,  405,  405,  415,  414,  406,
      430,  430,  430,  430,  413,  412,  431,  432,  430,  432,
      432,  411,  410,  433,  430,  430,  430,  430,  409,  408,
      431,  432,  430,  432,  432,  407,  402,  433,  442,  442,
      442,  442,  401,  400,  443,  444,  442,  444,  444,  397,

      396,  445,  442,  442,  442,  442,  395,  394,  443,  444,
      442,  444,  444,  393,  392,  445,   31,   31,   31,   45,
       45,   45,   51,   51,   51,   56,   56,   56,  102,  391,
      102,  107,  390,  107,  142,  389,  142,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,

      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  248,  247,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  114,  114,  226,  225,  224,  223,  222,  221,

      220,  219,  218,  217,  216,  114,  114,  215,  214,  213,
      212,  211,  210,  209,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      178,  177,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  164,  163,  162,  161,  159,  158,  154,  153,  152,
      151,  150,  149,  148,  146,  145,  114,  144,  114,  143,
      114,  141,  140,  138,  137,  136,  135,  134,  133,  132,
      131,  130,  129,  128,  127,  126,  125,  124,  123,  122,
      114,  121,  120,  119,  118,  114,  117,  114,  116,  114,

      115,  114,  450,  112,  111,  106,  100,   99,   96,   95,
       94,   93,   92,   91,   90,   89,   79,   78,   75,   68,
      450,   63,  450,   11,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450
    } ;

static yyconst flex_int16_t yy_chk[774] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,   20,  455,    3,    7,    7,    7,    7,
       13,  447,    7,   13,    3,    3,   23,    3,    3,   23,
       20,    3,    8,    8,    8,    8,  446,   27,    8,    3,
       27,    3,    3,   14,   14,   14,   14,  135,    3,    4,
        4,    4,    4,   27,  445,    4,    9,    9,    9,    9,

       28,  135,    9,   32,    4,    4,   32,    4,    4,  443,
       29,    4,   10,   10,   10,   10,   43,   28,   10,    4,
       43,    4,    4,   15,   15,   15,   15,  436,    4,    5,
        5,    5,    5,   46,   30,    5,   46,  435,    5,    5,
        5,    5,    5,    5,    6,    6,    6,    6,   29,   52,
        6,  434,   52,    6,    6,    6,    6,    6,    6,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   21,   30,   33,   33,   33,   33,   34,   34,   34,
       34,   57,  433,   21,   57,   21,   47,   47,   47,   47,
       21,  431,   17,   17,   17,   68,   68,   17,   49,   49,

       49,   49,   49,   53,   53,   53,   53,   54,   54,   54,
       54,   58,   58,   58,   58,   59,   59,   59,   59,   61,
      125,  125,   61,   62,   62,   62,   62,   65,   65,   65,
       65,   65,   88,   88,   88,   88,  101,  101,  101,  101,
      101,  103,  136,  136,  103,  104,  104,  104,  104,  105,
      105,  105,  105,  108,  190,  190,  108,  109,  109,  109,
      109,  110,  110,  110,  110,  113,  113,  113,  113,  113,
      113,  139,  139,  139,  139,  139,  147,  147,  147,  147,
      394,  394,  147,  157,  157,  157,  157,  425,  425,  157,
      160,  160,  160,  160,  160,  160,  165,  165,  165,  165,

      437,  437,  165,  176,  176,  176,  176,  429,  426,  176,
      179,  179,  179,  179,  179,  196,  196,  196,  196,  196,
      213,  232,  235,  424,  423,  421,  235,  420,  232,  419,
      232,  213,  398,  398,  398,  398,  418,  417,  398,  399,
      399,  399,  399,  414,  413,  399,  403,  403,  403,  403,
      412,  411,  403,  405,  405,  405,  405,  410,  409,  405,
      427,  427,  427,  427,  408,  407,  427,  428,  428,  428,
      428,  406,  404,  428,  430,  430,  430,  430,  402,  401,
      430,  432,  432,  432,  432,  400,  397,  432,  440,  440,
      440,  440,  396,  395,  440,  441,  441,  441,  441,  393,

      392,  441,  442,  442,  442,  442,  391,  390,  442,  444,
      444,  444,  444,  389,  387,  444,  451,  451,  451,  452,
      452,  452,  453,  453,  453,  454,  454,  454,  456,  386,
      456,  457,  385,  457,  458,  384,  458,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  373,  372,  371,  370,
      369,  367,  366,  365,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  325,  324,  323,  322,  321,  320,  319,  318,  317,

      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  288,  287,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  275,  273,  272,
      271,  270,  269,  268,  267,  265,  264,  263,  262,  261,
      260,  259,  258,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  234,  233,  231,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  212,  211,  210,  209,  208,  207,

      206,  205,  204,  203,  202,  200,  199,  198,  197,  195,
      194,  193,  192,  191,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  178,  177,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  164,  163,  162,  161,
      159,  158,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  144,  143,  141,  140,  138,  137,  134,  133,  132,
      131,  129,  127,  126,  124,  123,  122,  121,  120,  119,
      117,  116,  115,  111,  106,  100,   99,   98,   97,   96,
       95,   94,   93,   92,   91,   90,   89,   86,   84,   83,
       81,   80,   79,   78,   77,   76,   75,   74,   73,   72,

       70,   69,   64,   63,   60,   55,   48,   44,   42,   41,
       40,   39,   38,   37,   36,   35,   26,   25,   22,   19,
       18,   16,   11,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  450
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
/* busmaster_scanner.l
 *
 * Wiretap Library
 * Copyright (c) 1998 by Gilbert Ramirez <gram@alumni.rice.edu>
 *
 * Support for Busmaster log file format
 * Copyright (c) 2019 by Maksim Salau <maksim.salau@gmail.com>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#define YY_NO_INPUT 1
/*
 * We have to override the memory allocators so that we don't get
 * "unused argument" warnings from the yyscanner argument (which
 * we don't use, as we have a global memory allocator).
 *
 * We provide, as macros, our own versions of the routines generated by Flex,
 * which just call malloc()/realloc()/free() (as the Flex versions do),
 * discarding the extra argument.
 */
#line 45 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"

#include <ws_diag_control.h>
#include <wiretap/file_wrappers.h>
#include "busmaster_parser.h"
#include "busmaster_priv.h"

#ifndef HAVE_UNISTD_H
#define YY_NO_UNISTD_H
#endif

static int busmaster_yyinput(void *buf, unsigned int length, busmaster_state_t *state)
{
    int ret = file_read(buf, length, state->fh);

    if (ret < 0)
    {
        state->err = file_error(state->fh, &state->err_info);
        return YY_NULL;
    }

    return ret;
}

#define YY_INPUT(buf, result, max_size) \
    do { (result) = busmaster_yyinput((buf), (max_size), yyextra); } while (0)

/* Count bytes read. This is required in order to rewind the file
 * to the beginning of the next packet, since flex reads more bytes
 * before executing the action that does yyterminate(). */
#define YY_USER_ACTION do { yyextra->file_bytes_read += yyleng; } while (0);

/*
 * Sleazy hack to suppress compiler warnings in yy_fatal_error().
 */
#define YY_EXIT_FAILURE ((void)yyscanner, 2)

/*
 * Macros for the allocators, to discard the extra argument.
 */
#define busmaster_alloc(size, yyscanner)          (void *)malloc(size)
#define busmaster_realloc(ptr, size, yyscanner)   (void *)realloc((char *)(ptr), (size))
#define busmaster_free(ptr, yyscanner)            free((char *)(ptr))

DIAG_OFF_FLEX



#line 825 "/Users/miguel/Downloads/make/wiretap/busmaster_scanner.c"

#define INITIAL 0
#define HEADER 1
#define TIME 2
#define HEADER_CHANNELS 3
#define HEADER_DB_FILES 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE busmaster_state_t *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int busmaster_lex_init (yyscan_t* scanner);

int busmaster_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int busmaster_lex_destroy (yyscan_t yyscanner );

int busmaster_get_debug (yyscan_t yyscanner );

void busmaster_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE busmaster_get_extra (yyscan_t yyscanner );

void busmaster_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *busmaster_get_in (yyscan_t yyscanner );

void busmaster_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *busmaster_get_out (yyscan_t yyscanner );

void busmaster_set_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t busmaster_get_leng (yyscan_t yyscanner );

char *busmaster_get_text (yyscan_t yyscanner );

int busmaster_get_lineno (yyscan_t yyscanner );

void busmaster_set_lineno (int line_number ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int busmaster_wrap (yyscan_t yyscanner );
#else
extern int busmaster_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int busmaster_lex (yyscan_t yyscanner);

#define YY_DECL int busmaster_lex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 100 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"


#line 1049 "/Users/miguel/Downloads/make/wiretap/busmaster_scanner.c"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			busmaster_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				busmaster__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		busmaster__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 451 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 450 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 102 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 103 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyterminate(); };
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 104 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ YY_FATAL_ERROR("Unterminated header statement"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 106 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(HEADER); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 107 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(HEADER); return TOKEN_ENDL; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 108 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(INITIAL); yyterminate(); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ return TOKEN_HEADER_VER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 110 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = PROTOCOL_CAN;   return TOKEN_PROTOCOL_TYPE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 111 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = PROTOCOL_J1939; return TOKEN_PROTOCOL_TYPE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 112 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = PROTOCOL_LIN;   return TOKEN_PROTOCOL_TYPE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(TIME); return TOKEN_START_TIME; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 114 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(TIME); return TOKEN_END_TIME; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = DATA_MODE_DEC; return TOKEN_DATA_MODE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = DATA_MODE_HEX; return TOKEN_DATA_MODE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = TIME_MODE_ABSOLUTE; return TOKEN_TIME_MODE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = TIME_MODE_SYSTEM;   return TOKEN_TIME_MODE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 119 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = TIME_MODE_RELATIVE; return TOKEN_TIME_MODE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 120 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ return TOKEN_START_SESSION; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 121 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ return TOKEN_STOP_SESSION; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(HEADER_CHANNELS); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 123 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(HEADER_DB_FILES); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 124 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ return TOKEN_HEADER_CHAR; }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 126 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(HEADER); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 127 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
;
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 128 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
;
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 130 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(HEADER); }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 131 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ BEGIN(HEADER); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 132 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
;
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 133 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 135 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = strtoul(yytext, NULL, 10); return TOKEN_INT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 136 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ return TOKEN_COLON; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 137 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ return TOKEN_INVALID_CHAR; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 139 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{
                    char *endp;
                    char *strp;

                    yyextra->token.v0 = strtoul(yytext, &endp, 10);
                    if (*endp != ':' || endp == yytext)
                        return TOKEN_INVALID_NUMBER;

                    strp = endp + 1;
                    yyextra->token.v1 = strtoul(strp, &endp, 10);
                    if (*endp != ':' || endp == strp)
                        return TOKEN_INVALID_NUMBER;

                    strp = endp + 1;
                    yyextra->token.v2 = strtoul(strp, &endp, 10);
                    if (*endp != ':' || endp == strp)
                        return TOKEN_INVALID_NUMBER;

                    strp = endp + 1;
                    yyextra->token.v3 = strtoul(strp, &endp, 10);
                    if (*endp != '\0' || endp == strp)
                        return TOKEN_INVALID_NUMBER;

                    return TOKEN_MSG_TIME;
                }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 165 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{
                    char *endp;

                    if (yyextra->header.data_mode == DATA_MODE_HEX)
                        yyextra->token.v0 = strtoul(yytext, &endp, 16);
                    else if (yyextra->header.data_mode == DATA_MODE_DEC)
                        yyextra->token.v0 = strtoul(yytext, &endp, 10);
                    else
                        return TOKEN_INVALID_NUMBER;

                    if (*endp != '\0' || endp == yytext)
                        return TOKEN_INVALID_NUMBER;

                    return TOKEN_INT;
                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 181 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ return TOKEN_MSG_DIR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 182 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = MSG_TYPE_STD;     return TOKEN_MSG_TYPE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 183 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = MSG_TYPE_STD_RTR; return TOKEN_MSG_TYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 184 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = MSG_TYPE_EXT;     return TOKEN_MSG_TYPE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 185 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = MSG_TYPE_EXT_RTR; return TOKEN_MSG_TYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 186 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = MSG_TYPE_STD_FD;  return TOKEN_MSG_TYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 187 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = MSG_TYPE_EXT_FD;  return TOKEN_MSG_TYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 188 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ yyextra->token.v0 = MSG_TYPE_ERR;     return TOKEN_ERR_MSG_TYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 190 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{
    return TOKEN_J1939_MSG_TYPE;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 194 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
{ return TOKEN_INVALID_CHAR; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 196 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1402 "/Users/miguel/Downloads/make/wiretap/busmaster_scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(HEADER):
case YY_STATE_EOF(TIME):
case YY_STATE_EOF(HEADER_CHANNELS):
case YY_STATE_EOF(HEADER_DB_FILES):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * busmaster_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( busmaster_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of busmaster_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					busmaster_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			busmaster_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) busmaster_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 451 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 451 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 450);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					busmaster_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( busmaster_wrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void busmaster_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        busmaster_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            busmaster__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	busmaster__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	busmaster__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void busmaster__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		busmaster_pop_buffer_state();
	 *		busmaster_push_buffer_state(new_buffer);
     */
	busmaster_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	busmaster__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (busmaster_wrap()) processing, but the only time this flag
	 * is looked at is after busmaster_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void busmaster__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE busmaster__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) busmaster_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in busmaster__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) busmaster_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in busmaster__create_buffer()" );

	b->yy_is_our_buffer = 1;

	busmaster__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with busmaster__create_buffer()
 * @param yyscanner The scanner object.
 */
    void busmaster__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		busmaster_free((void *) b->yy_ch_buf ,yyscanner );

	busmaster_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a busmaster_restart() or at EOF.
 */
    static void busmaster__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	busmaster__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then busmaster__init_buffer was _probably_
     * called from busmaster_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void busmaster__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		busmaster__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void busmaster_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	busmaster_ensure_buffer_stack(yyscanner);

	/* This block is copied from busmaster__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from busmaster__switch_to_buffer. */
	busmaster__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void busmaster_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	busmaster__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		busmaster__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void busmaster_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)busmaster_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in busmaster_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)busmaster_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in busmaster_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE busmaster_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int busmaster_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int busmaster_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *busmaster_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *busmaster_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t busmaster_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *busmaster_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void busmaster_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void busmaster_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "busmaster_set_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void busmaster_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "busmaster_set_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see busmaster__switch_to_buffer
 */
void busmaster_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void busmaster_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int busmaster_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void busmaster_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* busmaster_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int busmaster_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) busmaster_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* busmaster_lex_init_extra has the same functionality as busmaster_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to busmaster_alloc in
 * the yyextra field.
 */

int busmaster_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    busmaster_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) busmaster_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    busmaster_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from busmaster_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * busmaster_lex_init()
     */
    return 0;
}

/* busmaster_lex_destroy is for both reentrant and non-reentrant scanners. */
int busmaster_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		busmaster__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		busmaster_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	busmaster_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        busmaster_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * busmaster_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    busmaster_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#line 196 "/Users/miguel/Downloads/wireshark-3.4.2/wiretap/busmaster_scanner.l"



DIAG_ON_FLEX

